# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06
import = [
    #"~/.config/alacritty/themes/themes/afterglow.toml"
    "~/.config/alacritty/catppuccin-mocha.toml"
]
[env]
TERM = "xterm-256color"

[shell] 
program = "/bin/zsh"
[window]

opacity = 1

padding.x = 8
padding.y =8 

[font]
size = 8.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"
[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"
[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"


